### ISSUE TITLE
Implement initial `chaos verify` command

### ISSUE THREAD

**Issue by russmiles** [chaosiq/chaosiq-cloud#34]
The new `chaos verify` command will:

1. Take an experiment with a custom `verification` block.
2. Reject an experiment if the custom `verification` block is not present, and does not have all `required` properties specified.
3. Split the incoming verification experiment into its constituent parts as experiment in their own right. For example, one experiment for the `steady-state-hypothesis`, one experiment for the `method`, and one experiment for the `rollbacks`.
4. Execute the `method` experiment, sending events to CIQ through the existing `control`.
5. Execute the `steady-state-hypothesis` experiment at the specified frequency and duration, sending events to CIQ through the existing `control`.
6. Execute the `rollbacks` experiment, sending events to CIQ through the existing `control`.

**Comment by dmartin35** [comment]
seems great @russmiles,  quick question though
do we wait for the end of the `method` experiment to run the `steady-state-hypothesis` experiment ? or do we run them in parallel ? 

i have a feeling a condition can take some time to be executed, while at the end of if, it might not have anymore impact on the SSH. wdyt ?

**Comment by russmiles** [comment]
It's an excellent question @dmartin35 , and I was considering options around this. I think, if it doesn't make things too awkward in implementation, that parallel makes sense. If anything, there might be value in an initial execution of a couple of SSHs _before_ the method is even executed; a type of "warm up" period? This could be an additional, optional verification parameter? wdyt?

**Comment by dmartin35** [comment]
I agree with running the SSH at least one, before triggering the condition.
I like the warm up idea. 

I could even think of choosing the time when to trigger to condition within the full time window. But this is clearly not for now, not for a first version.

really looking forward seeing this in action.

**Comment by dmartin35** [comment]
btw, it can be simply by using the `background` property of the action, to have non blocking condition.
this would leave the user responsible for choosing to either have a blocking or non-blocking condition against its SSH. 

let you choose what's the easiest for a first version. don't want to add extra load of work to you.

**Comment by russmiles** [comment]
Nice! Yep, I think a first version might be seeing how far the existing functionality can go, and then future versions will rapidly roll in greater control and more advanced needs if we really need them. Finding the simplest solution for now is the main part of the job on this I think so your input is great @dmartin35

**Comment by russmiles** [comment]
Contributed to by #35
